# Merge in all unique constants and mappings from utils/constants.py
# All SEMANTIC_ROLE_MAP, ENTITY_ID_SUFFIXES, COMMON_AREAS, etc. are unified here for registry use.

# Constants for registry migration
SETTINGS_FILE = 'settings.conf.yaml'
CONTRACT_FILE = 'contracts/expected_alpha_sensor_registry.yaml'
COMMON_AREAS = [
    'bedroom', 'kitchen', 'living_room', 'ensuite', 'desk', 'wardrobe',
    'downstairs', 'upstairs', 'ha_addons', 'system_admin', 'network_connectivity',
    'home', 'ha', 'area', 'zone', 'room', 'bathroom', 'garage', 'hallway', 'office',
    'utility', 'loft', 'basement', 'attic', 'entry', 'lounge', 'hestia', 'laundry',
    'virtual_devices'
]
ENTITY_ID_SUFFIXES = [
    '_temperature', '_humidity', '_pressure', '_battery', '_illuminance',
    '_motion', '_contact', '_occupancy', '_power', '_energy', '_voltage',
    '_current', '_signal', '_status', '_switch', '_sensor', '_light',
    '_lock', '_cover', '_fan', '_climate', '_alarm', '_smoke', '_co',
    '_co2', '_water', '_gas', '_sound', '_vibration', '_button', '_remote',
    '_scene', '_input', '_output', '_camera', '_media', '_device', '_group',
    '_zone', '_room', '_area', '_appliance', '_gateway', '_bridge', '_hub',
    '_controller', '_integration', '_addon', '_system', '_admin', '_network',
    '_connectivity', '_os', '_host', '_core', '_backup', '_forecast', '_sun',
    '_moon', '_weather', '_calendar', '_event', '_automation', '_script',
    '_timer', '_counter', '_number', '_select', '_text', '_date', '_time',
    '_datetime', '_binary', '_analog', '_digital', '_rfid', '_nfc', '_ble',
    '_zigbee', '_zha', '_zwave', '_mqtt', '_esphome', '_tasmota', '_deconz',
    '_homekit', '_google', '_alexa', '_apple', '_amazon', '_sonos', '_tplink',
    '_hue', '_ikea', '_tradfri', '_xiaomi', '_aqara', '_tuya', '_shelly',
    '_wemo', '_lifx', '_yeelight', '_arlo', '_ring', '_nest', '_ecobee',
    '_august', '_myq', '_roomba', '_neato', '_dyson', '_bosch', '_siemens',
    '_samsung', '_lg', '_panasonic', '_toshiba', '_sharp', '_philips',
    '_sony', '_jbl', '_bose', '_denon', '_onkyo', '_pioneer', '_yamaha',
    '_marantz', '_harman', '_kef', '_klipsch', '_polk', '_jamo', '_elac',
    '_qacoustics', '_monitor', '_audio', '_video', '_tv', '_projector',
    '_display', '_screen', '_monitor', '_speaker', '_soundbar', '_subwoofer',
    '_amplifier', '_receiver', '_dac', '_preamp', '_turntable', '_cd',
    '_dvd', '_bluetooth', '_wifi', '_ethernet', '_lan', '_wan', '_internet',
    '_cloud', '_local', '_remote', '_virtual', '_physical', '_test', '_dev',
    '_prod', '_stage', '_beta', '_alpha', '_gamma', '_delta', '_omega',
    '_sigma', '_pi', '_tau', '_phi', '_chi', '_psi', '_omega', '_zeta',
    '_lambda', '_kappa', '_theta', '_eta', '_iota', '_upsilon', '_omicron',
    '_xi', '_nu', '_mu', '_rho', '_beta', '_alpha', '_gamma', '_delta',
    '_epsilon', '_zeta', '_eta', '_theta', '_iota', '_kappa', '_lambda',
    '_mu', '_nu', '_xi', '_omicron', '_pi', '_rho', '_sigma', '_tau',
    '_upsilon', '_phi', '_chi', '_psi', '_omega'
]
SEMANTIC_ROLE_MAP = {
    'temperature': 'environment_sensor',
    'humidity': 'environment_sensor',
    'pressure': 'environment_sensor',
    'motion': 'occupancy_sensor',
    'contact': 'contact_sensor',
    'occupancy': 'occupancy_sensor',
    'power': 'power_sensor',
    'energy': 'energy_sensor',
    'voltage': 'voltage_sensor',
    'current': 'current_sensor',
    'signal': 'signal_sensor',
    'status': 'status_sensor',
    'switch': 'switch',
    'light': 'light',
    'lock': 'lock',
    'cover': 'cover',
    'fan': 'fan',
    'climate': 'climate',
    'alarm': 'alarm',
    'smoke': 'smoke_sensor',
    'co': 'co_sensor',
    'co2': 'co2_sensor',
    'water': 'water_sensor',
    'gas': 'gas_sensor',
    'sound': 'sound_sensor',
    'vibration': 'vibration_sensor',
    'button': 'button',
    'remote': 'remote',
    'scene': 'scene',
    'input': 'input',
    'output': 'output',
    'camera': 'camera',
    'media': 'media_device',
    'device': 'device',
    'group': 'group',
    'zone': 'zone',
    'room': 'room',
    'area': 'area',
    'appliance': 'appliance',
    'gateway': 'gateway',
    'bridge': 'bridge',
    'hub': 'hub',
    'controller': 'controller',
    'integration': 'integration',
    'addon': 'addon',
    'system': 'system',
    'admin': 'admin',
    'network': 'network',
    'connectivity': 'connectivity',
    'os': 'os',
    'host': 'host',
    'core': 'core',
    'backup': 'backup',
    'forecast': 'forecast',
    'sun': 'sun',
    'moon': 'moon',
    'weather': 'weather',
    'calendar': 'calendar',
    'event': 'event',
    'automation': 'automation',
    'script': 'script',
    'timer': 'timer',
    'counter': 'counter',
    'number': 'number',
    'select': 'select',
    'text': 'text',
    'date': 'date',
    'time': 'time',
    'datetime': 'datetime',
    'binary': 'binary_sensor',
    'analog': 'analog_sensor',
    'digital': 'digital_sensor',
    'rfid': 'rfid_sensor',
    'nfc': 'nfc_sensor',
    'ble': 'ble_device',
    'zigbee': 'zigbee_device',
    'zha': 'zha_device',
    'zwave': 'zwave_device',
    'mqtt': 'mqtt_device',
    'esphome': 'esphome_device',
    'tasmota': 'tasmota_device',
    'deconz': 'deconz_device',
    'homekit': 'homekit_device',
    'google': 'google_device',
    'alexa': 'alexa_device',
    'apple': 'apple_device',
    'amazon': 'amazon_device',
    'sonos': 'sonos_device',
    'tplink': 'tplink_device',
    'hue': 'hue_device',
    'ikea': 'ikea_device',
    'tradfri': 'tradfri_device',
    'xiaomi': 'xiaomi_device',
    'aqara': 'aqara_device',
    'tuya': 'tuya_device',
    'shelly': 'shelly_device',
    'wemo': 'wemo_device',
    'lifx': 'lifx_device',
    'yeelight': 'yeelight_device',
    'arlo': 'arlo_device',
    'ring': 'ring_device',
    'nest': 'nest_device',
    'ecobee': 'ecobee_device',
    'august': 'august_device',
    'myq': 'myq_device',
    'roomba': 'roomba_device',
    'neato': 'neato_device',
    'dyson': 'dyson_device',
    'bosch': 'bosch_device',
    'siemens': 'siemens_device',
    'samsung': 'samsung_device',
    'lg': 'lg_device',
    'panasonic': 'panasonic_device',
    'toshiba': 'toshiba_device',
    'sharp': 'sharp_device',
    'philips': 'philips_device',
    'sony': 'sony_device',
    'jbl': 'jbl_device',
    'bose': 'bose_device',
    'denon': 'denon_device',
    'onkyo': 'onkyo_device',
    'pioneer': 'pioneer_device',
    'yamaha': 'yamaha_device',
    'marantz': 'marantz_device',
    'harman': 'harman_device',
    'kef': 'kef_device',
    'klipsch': 'klipsch_device',
    'polk': 'polk_device',
    'jamo': 'jamo_device',
    'elac': 'elac_device',
    'qacoustics': 'qacoustics_device',
    'monitor': 'monitor_device',
    'audio': 'audio_device',
    'video': 'video_device',
    'tv': 'tv_device',
    'projector': 'projector_device',
    'display': 'display_device',
    'screen': 'screen_device',
    'monitor': 'monitor_device',
    'speaker': 'speaker_device',
    'soundbar': 'soundbar_device',
    'subwoofer': 'subwoofer_device',
    'amplifier': 'amplifier_device',
    'receiver': 'receiver_device',
    'dac': 'dac_device',
    'preamp': 'preamp_device',
    'turntable': 'turntable_device',
    'cd': 'cd_device',
    'dvd': 'dvd_device',
    'bluetooth': 'bluetooth_device',
    'wifi': 'wifi_device',
    'ethernet': 'ethernet_device',
    'lan': 'lan_device',
    'wan': 'wan_device',
    'internet': 'internet_device',
    'cloud': 'cloud_device',
    'local': 'local_device',
    'remote': 'remote_device',
    'virtual': 'virtual_device',
    'physical': 'physical_device',
    'test': 'test_device',
    'dev': 'dev_device',
    'prod': 'prod_device',
    'stage': 'stage_device',
    'beta': 'beta_device',
    'alpha': 'alpha_device',
    'gamma': 'gamma_device',
    'delta': 'delta_device',
    'omega': 'omega_device',
    'sigma': 'sigma_device',
    'pi': 'pi_device',
    'tau': 'tau_device',
    'phi': 'phi_device',
    'chi': 'chi_device',
    'psi': 'psi_device',
    'omega': 'omega_device',
    'zeta': 'zeta_device',
    'lambda': 'lambda_device',
    'kappa': 'kappa_device',
    'theta': 'theta_device',
    'eta': 'eta_device',
    'iota': 'iota_device',
    'upsilon': 'upsilon_device',
    'omicron': 'omicron_device',
    'xi': 'xi_device',
    'nu': 'nu_device',
    'mu': 'mu_device',
    'rho': 'rho_device',
    # fallback
    'default': 'generic_sensor'
}
ENTITY_FEATURES = [
    "motion", "presence", "temperature", "humidity", "light", "switch", "door", "window", "occupancy", "illuminance", "contact", "power", "energy", "battery", "fan", "alarm", "button", "lock", "climate", "media_player", "cover"
]

STANDARD_DEVICE_CLASSES = [
    "motion", "presence", "temperature", "humidity", "light", "switch", "door", "window", "occupancy", "illuminance", "contact", "power", "energy", "battery", "fan", "alarm", "button", "lock", "climate", "media_player", "cover"
]

greek_tiers = [
    "alpha", "beta", "gamma", "delta", "epsilon", "zeta", "eta", "theta", "iota", "kappa", "lambda", "mu", "nu", "xi", "omicron", "pi", "rho", "sigma", "tau", "upsilon", "phi", "chi", "psi", "omega"
]

FEATURE_ROLES = [
    "battery_monitor",
    "signal_monitor",
    "config_param",
    "tuning_param"
]

PRESERVE_AUXILIARY_FIELDS = [
    "area_id",
    "capabilities",
    "config_entry_id",
    "device_id",
    "disabled_by",
    "entity_category",
    "options",
    "original_device_class",
    "original_icon",
    "platform",
    "suggested_object_id",
    "supported_features",
    "translation_key",
    "unique_id",
    "unit_of_measurement",
    "previous_unique_id"
]
